# This is a basic workflow to help you get started with Actions

name: RemoteRun

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        description: 'Collecion Name'     
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -L -o /usr/local/bin/opa https://openpolicyagent.org/downloads/v0.36.1/opa_linux_amd64_static
          chmod 755 /usr/local/bin/opa
          echo "opa binary path..."
          which opa
          echo "helm binary path..."
          which helm
          python3 -m venv helloenv
          source helloenv/bin/activate
          pip install -U pip
          pip install -U prancer-basic
          prancer -v
          collection='${{ github.event.inputs.name }}'
          apikey="${APIKEY}"
          gittoken="${GITTOKEN}"
          prancer --db REMOTE --env QA --apitoken $apikey --gittoken $gittoken --company prancer-john $collection
        env:
          APIKEY: ${{ secrets.APIKEY }}
          GITTOKEN: ${{ secrets.GITTOKEN }}
